[versions]
compose-gradle-plugin = "1.9.3"
google-services-version = "4.4.4"
kotlin = "2.2.21"
agp = "8.12.0"
compose-plugin = "1.9.3"
ktor = "3.3.2"
google-services = "4.4.4"
gitlive-firebase = "2.4.0"
coroutines = "1.10.2"

[libraries]
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-gradle-plugin" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "gitlive-firebase" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive-firebase" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.9.4" }

[plugins]

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
gitlive-firebase = { id = "dev.gitlive.firebase-plugin", version.ref = "gitlive-firebase" }
